---
title: "Modeling with `r group_name` dataset"
output: html_document
date: "`r current_time`"
---

```{r ex_setup, include=FALSE}
knitr::opts_chunk$set(
  message = FALSE,
  digits = 3,
  collapse = TRUE,
  comment = "|  ",
  warning=FALSE
  )
options(digits = 3, warn=-1)
```

## Prepare

- library読み込み
```{r prepare}
suppressWarnings(library(caret))
suppressWarnings(library(bnlearn))
suppressWarnings(library(bnviewer))
suppressWarnings(library(tidyverse))
suppressWarnings(library(conflicted))
conflict_prefer("filter", "dplyr")
conflict_prefer("lag", "dplyr")
```

- データ読み込み
```{r load data}
col_names <- c("preg","plas","pres","skin","test","mass","pedi","age","class")

df <- readr::read_csv("/home/rstudio/kitematic/ml_auto/data/pima-indians-diabetes.csv", 
                      col_names = col_names,
                      skip = 1) %>% 
  mutate_at(.vars = ("class"), as.factor)
```

- train・testに分割
```{r split}
trainIndex <- createDataPartition(df$class, p=2/3, list=FALSE, times=1)
train <- df[trainIndex,] %>% as.data.frame()
test <- df[-trainIndex,] %>% as.data.frame()
```

## Modeling

- 構造学習(モデル構築)
```{r st}
model_tabu_boot <- boot.strength(data = train, 
                                 R = 50,
                                 algorithm = "tabu")
model_tabu <- model_tabu_boot %>% averaged.network() %>% 
  pdag2dag(ordering = df %>% colnames())

model_hc_boot <- boot.strength(data = train, 
                              R = 50,
                              algorithm = "hc")
model_hc <- model_hc_boot %>% averaged.network() %>% 
  pdag2dag(ordering = df %>% colnames())
```

- 条件付確率表を計算
```{r fit}
model_tabu_fitted <- bn.fit(x = model_tabu, data = train)
model_hc_fitted <- bn.fit(x = model_hc, data = train)
```

## 予測

- testデータで分類
```{r pred in test}
prob_tabu <- predict(model_tabu_fitted, 
                     data = test %>% mutate(class=NULL), 
                     method="bayes-lw",
                     node="class")

prob_hc <- predict(model_hc_fitted, 
                   data = test %>% mutate(class=NULL), 
                   method="bayes-lw",
                   node="class")
```

- 性能評価 tabu
```{r check tabu}
cm_tabu <- confusionMatrix(prob_tabu, test$class, positive="1")
print(cm_tabu)
```

```{r check hc}
cm_hc <- confusionMatrix(prob_hc, test$class, positive="1")
print(cm_hc)
```

## 可視化

- plot hhmc
```{r plot tabu}
viewer(model_tabu)
```

- plot hc
```{r plot hc}
viewer(model_hc)
```
